import { app, BrowserWindow } from 'electron';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const GOOGLE_ACCOUNT_URL = 'https://myaccount.google.com/';

const buildCalendarUrl = (email: string): string =>
  `https://calendar.google.com/calendar/embed?src=${encodeURIComponent(email)}&ctz=Asia%2FTokyo&showPrint=0&mode=WEEK`;

const EMAIL_EXTRACTION_SCRIPT = `(() => {
  const emailPattern = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i;
  const pickEmail = (value) => {
    if (!value) return null;
    const matched = String(value).match(emailPattern);
    return matched ? matched[0] : null;
  };

  const selectors = [
    'a[href*="SignOutOptions"]',
    '[data-email]',
    '[aria-label*="@"]',
    '[title*="@"]',
  ];

  for (const selector of selectors) {
    const nodes = document.querySelectorAll(selector);
    for (const node of nodes) {
      const candidates = [
        node.getAttribute('data-email'),
        node.getAttribute('email'),
        node.getAttribute('aria-label'),
        node.getAttribute('title'),
        node.textContent,
      ];

      for (const candidate of candidates) {
        const email = pickEmail(candidate);
        if (email) return email;
      }
    }
  }

  return pickEmail(document.body?.innerText ?? '');
})()`;

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the requested page.
  mainWindow.loadURL(GOOGLE_ACCOUNT_URL);

  let lastLoggedEmail: string | null = null;

  const logGoogleEmail = async (): Promise<boolean> => {
    if (!mainWindow.webContents.getURL().startsWith(GOOGLE_ACCOUNT_URL)) {
      return false;
    }

    try {
      const email = (await mainWindow.webContents.executeJavaScript(EMAIL_EXTRACTION_SCRIPT, true)) as string | null;
      if (!email || email === lastLoggedEmail) {
        return false;
      }

      lastLoggedEmail = email;
      console.log(`[google-account] Logged in email: ${email}`);
      mainWindow.loadURL(buildCalendarUrl(email));
      return true;
    } catch (error) {
      console.error('[google-account] Failed to read email from page', error);
      return false;
    }
  };

  mainWindow.webContents.on('did-finish-load', () => {
    let attempts = 0;
    const maxAttempts = 15;

    const timerId = setInterval(() => {
      attempts += 1;
      void logGoogleEmail().then((found) => {
        if (found || attempts >= maxAttempts) {
          clearInterval(timerId);
        }
      });
    }, 2000);
  });

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    mainWindow.loadURL(url);
    return { action: 'deny' };
  });

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
